name: Trigger a release build

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Release version
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare environment
        run: |
          git config --global user.email "SirKnightlySCP@gmail.com"
          git config --global user.name "SirKnightly"
      - name: Checkout nightly script
        uses: actions/checkout@v2
      - name: Decrypt config
        env:
          CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$CONFIG_PASSWORD" --output $GITHUB_WORKSPACE/config.yml config.github.yml.gpg
      - name: Checkout FSO code
        uses: actions/checkout@v2
        with:
          repository: asarium/fs2open.github.com
          path: fs2open.github.com
          ssh-key: ${{ secrets.SIRKNIGHTLY_PRIVATE_KEY }}
          submodules: true
          fetch-depth: 0
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run script
        run: |
          python release.py --config $GITHUB_WORKSPACE/config.yml ${{ github.event.inputs.releaseVersion }}